2023-06-28 06:30:25,173 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-06-28 06:30:25,174 INFO supervisord started with pid 6
2023-06-28 06:30:26,176 INFO spawned: 'nginx' with pid 9
2023-06-28 06:30:26,177 INFO spawned: 'app' with pid 10
2023-06-28 06:30:27,188 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-28 06:30:27,188 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 28.06.23 06:30:29] [Level: info] id: 1e97d70848aa3532
[Time: 28.06.23 06:30:29] [Level: info] coordinator: False
[Time: 28.06.23 06:30:29] [Level: info] clients: ['1e97d70848aa3532', '70bfe26f943d1ae0']
[Time: 28.06.23 06:30:29] [Level: info] state: initial
[CLIENT] Parsing parameter file...
[API] /setup parsing parameter file 
[API] /setup config file found ... parsing file: /mnt/input/config.yaml
YAML file does not follow specification: missing key: eigenvalues
Setting default: eigenvalues.tsv
YAML file does not follow specification: missing key: explained_variance
Setting default: eigenvalues.tsv
YAML file does not follow specification: missing key: output delimiter
Setting default: tab
[API] /setup config file found ... parsing done
[CLIENT] finished parsing parameter file.
[STARTUP] Instantiate SVD
[STARTUP] Copy configuration and create dir
TEST: ['/mnt/input/hospital_data_bredel_1.csv']
[STARTUP] Configuration copied
Log Transform performed
/app/apps/svd/FC_Federated_MFA.py:125: RuntimeWarning: invalid value encountered in log2
  tabdata.scaled = np.log2(tabdata.scaled+1)
[Time: 28.06.23 06:30:29] [Level: info] transition: wait_for_params
[Time: 28.06.23 06:30:30] [Level: info] state: wait_for_params
[CTRL] GET /data
[CTRL] POST /data
setting parameters
[API] Setting parameters
[Time: 28.06.23 06:30:33] [Level: info] Traceback (most recent call last):
  File "/app/engine/app.py", line 169, in guarded_run
    self.run()
  File "/app/engine/app.py", line 184, in run
    transition = self.current_state.run()
  File "/app/apps/svd/app.py", line 100, in run
    self.load('mfa').set_parameters(incoming)
  File "/app/apps/svd/FC_Federated_MFA.py", line 145, in set_parameters
    self.k[idx] = incoming[COParams.PCS.n]
IndexError: list assignment index out of range

