2023-06-29 13:38:15,018 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-06-29 13:38:15,020 INFO supervisord started with pid 7
2023-06-29 13:38:16,023 INFO spawned: 'nginx' with pid 10
2023-06-29 13:38:16,025 INFO spawned: 'app' with pid 11
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 22, in register
    self.register_transition('initial_pca', Role.BOTH)
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 29.06.23 13:38:16] [Level: fatal] target state initial_pca not found
2023-06-29 13:38:16,926 INFO exited: app (exit status 1; not expected)
2023-06-29 13:38:17,928 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-06-29 13:38:17,930 INFO spawned: 'app' with pid 47
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 22, in register
    self.register_transition('initial_pca', Role.BOTH)
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 29.06.23 13:38:18] [Level: fatal] target state initial_pca not found
2023-06-29 13:38:18,579 INFO exited: app (exit status 1; not expected)
2023-06-29 13:38:20,584 INFO spawned: 'app' with pid 71
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 22, in register
    self.register_transition('initial_pca', Role.BOTH)
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 29.06.23 13:38:20] [Level: fatal] target state initial_pca not found
2023-06-29 13:38:21,104 INFO exited: app (exit status 1; not expected)
2023-06-29 13:38:24,109 INFO spawned: 'app' with pid 95
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 22, in register
    self.register_transition('initial_pca', Role.BOTH)
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 293, in register_transition
    self.log(f'target state {target} not found', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 29.06.23 13:38:24] [Level: fatal] target state initial_pca not found
2023-06-29 13:38:24,773 INFO exited: app (exit status 1; not expected)
2023-06-29 13:38:25,774 INFO gave up: app entered FATAL state, too many start retries too quickly
