2023-07-01 09:25:04,225 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-07-01 09:25:04,229 INFO supervisord started with pid 7
2023-07-01 09:25:05,232 INFO spawned: 'nginx' with pid 10
2023-07-01 09:25:05,235 INFO spawned: 'app' with pid 11
2023-07-01 09:25:06,279 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-01 09:25:06,279 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:06] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:06,906 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:07,909 INFO spawned: 'app' with pid 47
2023-07-01 09:25:08,911 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:09] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:09,486 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:10,490 INFO spawned: 'app' with pid 71
2023-07-01 09:25:11,492 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:11] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:11,902 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:12,906 INFO spawned: 'app' with pid 95
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:13] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:13,882 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:14,887 INFO spawned: 'app' with pid 119
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:15] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:15,984 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-07-01 09:25:15,985 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:16,988 INFO spawned: 'app' with pid 143
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:17] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:17,948 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:18,950 INFO spawned: 'app' with pid 167
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:19] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:19,525 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:21,530 INFO spawned: 'app' with pid 191
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:22] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:22,480 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:25,485 INFO spawned: 'app' with pid 215
Traceback (most recent call last):
  File "/app/main.py", line 14, in <module>
    app.register()
  File "/app/engine/app.py", line 202, in register
    state.register()
  File "/app/apps/svd/app.py", line 551, in register
    self.register_transition('separate_pca', Role.BOTH) 
  File "/app/engine/app.py", line 424, in register_transition
    self._app.register_transition(f'{self.name}_{name}', self.name, target, participant, coordinator)
  File "/app/engine/app.py", line 287, in register_transition
    self.log(f'source state {source} not accessible for participants', level=LogLevel.FATAL)
  File "/app/engine/app.py", line 340, in log
    raise RuntimeError(msg)
RuntimeError: [Time: 01.07.23 09:25:25] [Level: fatal] source state share_projections not accessible for participants
2023-07-01 09:25:26,045 INFO exited: app (exit status 1; not expected)
2023-07-01 09:25:27,047 INFO gave up: app entered FATAL state, too many start retries too quickly
